version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    env_file:
      - .env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend/crm_frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:80"
    env_file:
      - .env
    depends_on:
      - backend
